# Compose file for AMD GPU

services:

# Ref: https://hub.docker.com/r/rocm/pytorch
# Ref: https://rocm.docs.amd.com/projects/install-on-linux/en/latest/how-to/docker.html

  comfyui:
    init: true
    container_name: comfyui-rocm7
    build:
      context: .
      dockerfile: Dockerfile
    image: "localhost/comfyui-boot:rocm7"
    networks:
      - internal
    ports:
      - "8188:8188"
    volumes:
       - "~/.comfyui:/root"
    environment:
      HSA_OVERRIDE_GFX_VERSION: 12.0.1
      HIP_VISIBLE_DEVICES: "1,0"
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - label:disable

networks:
  internal:
    driver: bridge
    internal: true  # No external access
